name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Health check
        run: |
          sw_vers
          xcrun --find xcodebuild
          xcrun --find swift-format
          ls /Applications
          which xcpretty

      - uses: actions/checkout@v4

      - name: Lint
        run: xcrun swift-format lint -r .

      - name: Build IPA
        run: |
          xcodebuild -project MoneyFeedback.xcodeproj \
                     -scheme MoneyFeedback \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -archivePath MoneyFeedback.xcarchive \
                     archive
          
          xcodebuild -exportArchive \
                     -archivePath MoneyFeedback.xcarchive \
                     -exportPath . \
                     -exportOptionsPlist MoneyFeedback/ExportOptions.plist
